import { StyleSheet } from 'react-native';

export const registerStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0A0A0A',
    position: 'relative',
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: 20,
    paddingTop: 60,
  },
  registerBox: {
    backgroundColor: 'rgba(30, 31, 38, 0.95)',
    borderRadius: 16,
    padding: 30,
    marginTop: 40,
  },
  title: {
    fontSize: 32,
    fontFamily: 'LexendDeca-Bold',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 24,
    fontFamily: 'LexendDeca-Regular',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 32,
    opacity: 0.8,
  },
  formRow: {
    flexDirection: 'row',
    gap: 12,
  },
  formGroup: {
    marginBottom: 16,
  },
  label: {
    color: '#FFFFFF',
    fontSize: 14,
    fontFamily: 'LexendDeca-Regular',
    marginBottom: 8,
  },
  input: {
    width: '100%',
    padding: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 8,
    color: '#FFFFFF',
    fontSize: 16,
    fontFamily: 'LexendDeca-Regular',
  },
  passwordWrapper: {
    position: 'relative',
  },
  passwordInput: {
    paddingRight: 50,
  },
  passwordToggle: {
    position: 'absolute',
    right: 12,
    top: 12,
    padding: 4,
  },
  termsGroup: {
    marginBottom: 24,
  },
  termsLabel: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderWidth: 2,
    borderColor: '#6366f1',
    borderRadius: 4,
    marginRight: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxChecked: {
    backgroundColor: '#6366f1',
  },
  termsText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontFamily: 'LexendDeca-Regular',
    flex: 1,
  },
  termsLink: {
    color: '#6366f1',
    fontFamily: 'LexendDeca-Regular',
  },
  haveAccount: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
  },
  haveAccountText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontFamily: 'LexendDeca-Regular',
  },
  loginLink: {
    color: '#6366f1',
    fontSize: 14,
    fontFamily: 'LexendDeca-Regular',
  },
  buttonContainer: {
    gap: 18,
  },
  submitButton: {
    backgroundColor: '#835BFC',
    paddingVertical: 16,
    borderRadius: 8,
    alignItems: 'center',
  },
  submitButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontFamily: 'LexendDeca-SemiBold',
  },
  googleButton: {
    backgroundColor: 'rgba(131, 91, 252, 0.43)',
    paddingVertical: 14,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
  },
  googleIcon: {
    width: 24,
    height: 24,
  },
  googleButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontFamily: 'LexendDeca-SemiBold',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#1a1a1a',
    padding: 32,
    borderRadius: 12,
    width: '90%',
    maxWidth: 400,
    borderWidth: 1,
    borderColor: '#835BFC',
  },
  modalTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontFamily: 'LexendDeca-SemiBold',
    textAlign: 'center',
    marginBottom: 16,
  },
  modalText: {
    color: '#CCCCCC',
    fontFamily: 'LexendDeca-Regular',
    textAlign: 'center',
    marginBottom: 8,
  },
  emailText: {
    color: '#835BFC',
    fontFamily: 'LexendDeca-Medium',
    textAlign: 'center',
    marginBottom: 24,
  },
  verificationInput: {
    backgroundColor: '#2a2a2a',
    borderWidth: 1,
    borderColor: '#835BFC',
    borderRadius: 8,
    padding: 16,
    color: '#FFFFFF',
    fontSize: 16,
    fontFamily: 'LexendDeca-Regular',
    letterSpacing: 8,
    textAlign: 'center',
    marginBottom: 24,
  },
  modalButtons: {
    flexDirection: 'row',
    gap: 16,
  },
  cancelButton: {
    flex: 1,
    backgroundColor: '#2a2a2a',
    paddingVertical: 12,
    borderRadius: 6,
    alignItems: 'center',
  },
  cancelButtonText: {
    color: '#FFFFFF',
    fontFamily: 'LexendDeca-Medium',
  },
  verifyButton: {
    flex: 1,
    backgroundColor: '#835BFC',
    paddingVertical: 12,
    borderRadius: 6,
    alignItems: 'center',
  },
  verifyButtonText: {
    color: '#FFFFFF',
    fontFamily: 'LexendDeca-Medium',
  },
  termsScroll: {
    maxHeight: 200,
    marginBottom: 16,
  },
  termsFullText: {
    color: '#CCCCCC',
    fontFamily: 'LexendDeca-Regular',
    textAlign: 'justify',
    lineHeight: 20,
  },
});